# Site
name: "Watchdog"
description: "Cool stuffs about Computer Vision and Robotics."
meta_description: "computer vision , robotics  ,rgbd , odometry , kalman filter."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
google_analytics: 'UA-121671993-1'
disqus: 'debrupdatta'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

# Authors
authors:
  debrup:
    name: debrup
    display_name: debrup
    gravatar: 2fac263ee9f47b1c037ee2f1e2aa43a7
    email: dattadebrup@gmail.com
    web: https://dattadebrup.github.io
    twitter: https://twitter.com/DEBRUPDATTA
    description: ""
    

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge
